# Generated by Django 5.1.4 on 2025-01-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0007_remove_estadistica_mesero_pedidosatendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica_mesa',
            name='mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_mesa', to='Estadisticas.mesa'),
        ),
        migrations.AddField(
            model_name='estadistica_mesero',
            name='mesero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_mesero', to='Estadisticas.mesero'),
        ),
        migrations.AddField(
            model_name='estadistica_producto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_producto', to='Estadisticas.producto'),
        ),
    ]
