# Generated by Django 5.1.4 on 2025-01-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0008_estadistica_mesa_mesa_estadistica_mesero_mesero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica_mesa',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='estadistica_mesero',
            name='mesero',
        ),
        migrations.RemoveField(
            model_name='estadistica_producto',
            name='producto',
        ),
    ]
