# Generated by Django 5.1.4 on 2025-01-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0010_remove_estadistica_mesa_factura_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica_mesero',
            name='mejor_mesero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_mesero', to='Estadisticas.mesero'),
        ),
    ]
