# Generated by Django 5.1.4 on 2025-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0013_alter_estadistica_mesero_mejor_mesero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica_mesero',
            name='mejor_mesero',
            field=models.CharField(max_length=50),
        ),
    ]
